# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push]
    
jobs:
  # makes sure the project can compile
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x' # version in go.mod
        
    - name: Download Go Dependencies
      run: go get .
      
    - name: Build
      run: go build -v ./...

  # run test in the test file directory
  test:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash ./publish-script.sh
      
    
